slices:
  - sources:
      - model: TinyLlama/TinyLlama-1.1B-Chat-v1.0
        layer_range: [0, 5]
      - model: garage-bAInd/Platypus2-13B
        layer_range: [0, 5]
merge_method: slerp
base_model: TinyLlama/TinyLlama-1.1B-Chat-v1.0
parameters:
  t:
    - filter: self_attn
      value: [0, 0.5, 0.3, 0.7, 1]
    - filter: mlp
      value: [1, 0.5, 0.7, 0.3, 0]
    - value: 0.5 # fallback for rest of tensors
dtype: float16
